import { gql } from '@apollo/client';
import styled from '@emotion/styled';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Hero, HostedSection, IntroSection } from '@components';
import { client } from '../lib/apollo';
import { Fragment } from 'react';

const imgPath =
	'https://jelmoreassets.nyc3.cdn.digitaloceanspaces.com/SlipstreamRacing/Home';

const Home: NextPage = ({ data }: any) => {
	const { copy, youtubeLink } = data;
	return (
		<Fragment>
			<Head>
				<meta
					name='description'
					content='Generated by create next app'
				/>
			</Head>
			<Hero backgroundImage={`${imgPath}/hero.png`} />
			<IntroSection copy={copy} youtubeLink={youtubeLink} />
			<HostedSection src={`${imgPath}/simracinggp-wordmark.svg`} />
		</Fragment>
	);
};

export default Home;

export async function getStaticProps() {
	const results = await client.query({
		query: gql`
			query GetHomePage {
				page(id: "/", idType: URI) {
					homePage {
						copy
						youtubeLink
					}
				}
			}
		`,
	});

	return {
		props: {
			data: results.data.page.homePage,
		},
	};
}
